# Generated by Django 4.0.1 on 2022-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.Field()),
                ('password', models.Field()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
